name: flutter_proj_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: 
  go_router:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Thin.ttf
          weight: 100
        # - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraLight.ttf
        #   weight: 200
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        # - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-SemiBold.ttf
        #   weight: 600
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Black.ttf
          weight: 800

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        # - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
        #   weight: 200
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        # - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
        #   weight: 600
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        # - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
        #   weight: 800
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        